# Generated by Django 5.2.4 on 2025-07-26 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_recruiterid_alter_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talents', to='api.event')),
            ],
        ),
    ]
