# Generated by Django 5.2.4 on 2025-08-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recruiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talent',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='user',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='talent',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
