# Generated by Django 5.2.4 on 2025-08-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_talent_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
