# Generated by Django 5.2.4 on 2025-07-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_talent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='event',
        ),
        migrations.AlterField(
            model_name='talent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
