# Generated by Django 5.2.4 on 2025-07-28 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_talent_event_alter_talent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_timeSlot_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attending', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('note', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.talent')),
            ],
            options={
                'unique_together': {('talent', 'event')},
            },
        ),
    ]
