# Generated by Django 5.2.4 on 2025-09-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_recruiter_phone_remove_talent_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
