# Generated by Django 5.2.4 on 2025-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='rdv',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
