# Generated by Django 5.2.4 on 2025-07-28 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_event_time_slot_participation_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeSlot', to='api.timeslot'),
        ),
    ]
