# Generated by Django 5.2.4 on 2025-07-28 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_participation_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='participation',
            name='event_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.timeslot'),
        ),
    ]
