# Generated by Django 5.2.4 on 2025-08-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_event_is_online_alter_event_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='caption',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
