# Generated by Django 5.2.4 on 2025-08-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recruiters_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
