# Generated by Django 5.2.4 on 2025-08-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_event_recruiters_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
