# Generated by Django 5.2.4 on 2025-08-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='is_attending',
            new_name='has_attended',
        ),
        migrations.AlterField(
            model_name='participation',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
