# Generated by Django 5.2.4 on 2025-08-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_is_attending_participation_has_attended_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='talent',
            new_name='talent_id',
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('talent_id', 'event_id')},
        ),
    ]
