# Generated by Django 5.2.4 on 2025-08-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_event_participation_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='etablissement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='filiere',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
