# Generated by Django 5.2.4 on 2025-08-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_convert_rdv_to_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
